apiVersion: v1
data:
  username: dXNlcjE=
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:username: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
  name: test-secret
  namespace: cluster-config
type: Opaque
